# Generated by Django 4.2.30 on 2026-06-16 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)])),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('goal', models.CharField(choices=[('HYPERTROPHY', 'Hypertrophy'), ('STRENGTH', 'Strength'), ('FAT_LOSS', 'Fat Loss'), ('RECOMPOSITION', 'Recomposition'), ('GENERAL_FITNESS', 'General Fitness')], max_length=30)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=30)),
                ('training_experience', models.CharField(choices=[('LESS_THAN_1', '< 1 year'), ('ONE_TO_THREE', '1-3 years'), ('THREE_TO_FIVE', '3-5 years'), ('MORE_THAN_FIVE', '> 5 years')], max_length=30)),
                ('days_per_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
