# =============================================================================
# 0002_rename_is_failure_setlog_reached_failure_and_more.py
# -----------------------------------------------------------------------------
# Migração Django da app progression.
# É usada pelo sistema de migrations para criar ou alterar a estrutura da base de dados associada a progression.
# O ficheiro 0002_rename_is_failure_setlog_reached_failure_and_more deve ser mantido como histórico técnico da evolução dos modelos e aplicado automaticamente pelo manage.py migrate.
# =============================================================================
# Generated by Django 4.2.30 on 2026-06-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlog',
            old_name='is_failure',
            new_name='reached_failure',
        ),
        migrations.RenameField(
            model_name='setlog',
            old_name='reps',
            new_name='reps_completed',
        ),
        migrations.RenameField(
            model_name='setlog',
            old_name='weight',
            new_name='weight_used',
        ),
        migrations.AddField(
            model_name='setlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='planned_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='target_max_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='target_min_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='training_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='training.trainingworkoutexercise'),
        ),
    ]
