# Generated by Django 4.2.30 on 2026-06-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_workoutsession'),
        ('progression', '0002_rename_is_failure_setlog_reached_failure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlog',
            name='workout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='training.workoutsession'),
        ),
    ]
