# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progression", "0003_setlog_workout_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="setlog",
            name="set_type",
            field=models.CharField(
                choices=[
                    ("WARMUP", "Warm-up"),
                    ("WORKING", "Working set"),
                    ("DROP", "Drop set"),
                ],
                default="WORKING",
                max_length=20,
            ),
        ),
    ]
