# Generated by Codex on 2026-06-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_difficulty_exercise_is_compound_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0002_workoutsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteTrainingMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("memory_type", models.CharField(choices=[("PROGRESSION", "Progression"), ("WATCHLIST", "Watchlist"), ("EFFORT_PATTERN", "Effort pattern")], max_length=30)),
                ("title", models.CharField(max_length=120)),
                ("summary", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("confidence", models.CharField(default="média", max_length=20)),
                ("severity", models.PositiveIntegerField(default=1)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="training_memories", to="exercises.exercise")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="training_memories", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-severity", "-updated_at"],
                "unique_together": {("user", "exercise", "memory_type")},
            },
        ),
    ]
