# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_difficulty_exercise_is_compound_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0003_athletetrainingmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptivePlanDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workout_name", models.CharField(max_length=100)),
                ("exercise_name", models.CharField(max_length=100)),
                ("action", models.CharField(choices=[("protect_recovery", "Protect recovery"), ("increase_margin", "Increase margin"), ("progress_load", "Progress load"), ("maintain_plan", "Maintain plan")], max_length=30)),
                ("status", models.CharField(choices=[("APPLIED", "Applied"), ("DEFERRED", "Deferred"), ("IGNORED", "Ignored")], max_length=20)),
                ("current_sets", models.PositiveIntegerField()),
                ("recommended_sets", models.PositiveIntegerField()),
                ("current_target_rir", models.PositiveIntegerField()),
                ("recommended_target_rir", models.PositiveIntegerField()),
                ("load_adjustment", models.FloatField(default=0)),
                ("message", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adaptive_plan_decisions", to="exercises.exercise")),
                ("training_exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adaptive_plan_decisions", to="training.trainingworkoutexercise")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adaptive_plan_decisions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
