# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0004_adaptiveplandecision"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")], default="ACTIVE", max_length=20)),
                ("phase", models.CharField(choices=[("BUILD", "Build"), ("DELOAD", "Deload"), ("RETURN", "Return")], default="BUILD", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("planned_weeks", models.PositiveIntegerField(default=4)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="training_blocks", to="training.trainingprogram")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="training_blocks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
    ]
