# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_userexerciseweightscale"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="coach_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="coach_feedback_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="coach_feedback_source",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="coach_feedback_status",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
