# =============================================================================
# 0001_initial.py
# -----------------------------------------------------------------------------
# Migração Django da app exercises.
# É usada pelo sistema de migrations para criar ou alterar a estrutura da base de dados associada a exercises.
# O ficheiro 0001_initial deve ser mantido como histórico técnico da evolução dos modelos e aplicado automaticamente pelo manage.py migrate.
# =============================================================================
# Generated by Django 4.2.30 on 2026-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
            ],
        ),
    ]
