# Generated by Django 4.2.30 on 2026-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(choices=[('HORIZONTAL_PUSH', 'Horizontal Push'), ('VERTICAL_PUSH', 'Vertical Push'), ('HORIZONTAL_PULL', 'Horizontal Pull'), ('VERTICAL_PULL', 'Vertical Pull'), ('SQUAT', 'Squat'), ('HINGE', 'Hinge'), ('LUNGE', 'Lunge'), ('HIP_THRUST', 'Hip Thrust'), ('ISOLATION', 'Isolation'), ('CORE', 'Core'), ('CARDIO', 'Cardio')], default='ISOLATION', max_length=50),
        ),
    ]
