# =============================================================================
# 0003_exercise_image_localized_name.py
# -----------------------------------------------------------------------------
# Migração Django da app exercises.
# É usada pelo sistema de migrations para criar ou alterar a estrutura da base de dados associada a exercises.
# O ficheiro 0003_exercise_image_localized_name deve ser mantido como histórico técnico da evolução dos modelos e aplicado automaticamente pelo manage.py migrate.
# =============================================================================
# Generated by Codex on 2026-06-25

from django.db import migrations, models


EXERCISE_CATALOG = [
    ("Lat Pulldown", "Puxada Alta na Polia (Máquina)", "Back", "Machine", "VERTICAL_PULL", True, "/exercise-screens/IMG_3620.PNG"),
    ("Seated Row Machine", "Remada Sentada com Pegada em V (Cabo)", "Back", "Cable", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3620.PNG"),
    ("Assisted Pull Up Machine", "Barra Fixa no Graviton (Máquina)", "Back", "Machine", "VERTICAL_PULL", True, "/exercise-screens/IMG_3620.PNG"),
    ("Rear Delt Fly", "Aberturas Invertidas de Ombro Posterior (Máquina)", "Shoulders", "Machine", "HORIZONTAL_PULL", False, "/exercise-screens/IMG_3620.PNG"),
    ("Barbell Curl", "Rosca Direta (Barra)", "Biceps", "Barbell", "ISOLATION", False, "/exercise-screens/IMG_3620.PNG"),
    ("Hammer Curl", "Rosca Martelo (Halter)", "Biceps", "Dumbbell", "ISOLATION", False, "/exercise-screens/IMG_3620.PNG"),
    ("Chest Press Machine", "Supino Sentado (Máquina)", "Chest", "Machine", "HORIZONTAL_PUSH", True, "/exercise-screens/IMG_3620.PNG"),
    ("Pec Deck", "Pec Deck", "Chest", "Machine", "HORIZONTAL_PUSH", False, "/exercise-screens/IMG_3621.PNG"),
    ("Shoulder Press", "Prensa de Ombros (Sentada) (Máquina)", "Shoulders", "Machine", "VERTICAL_PUSH", True, "/exercise-screens/IMG_3621.PNG"),
    ("Triceps Pushdown", "Tríceps na Polia com Corda", "Triceps", "Cable", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Dumbbell Lateral Raise", "Elevação Lateral (Halter)", "Shoulders", "Dumbbell", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Leg Press", "Leg Press Horizontal (Máquina)", "Quadriceps", "Machine", "SQUAT", True, "/exercise-screens/IMG_3621.PNG"),
    ("Seated Leg Curl", "Cadeira Flexora (Máquina)", "Hamstrings", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Adductor Machine", "Cadeira Adutora (Máquina)", "Adductors", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Iso Lateral Row Machine", "Remadas Iso-Lateral (Máquina)", "Back", "Machine", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3621.PNG"),
    ("Twenty One Curl", "Rosca 21", "Biceps", "Barbell", "ISOLATION", False, "/exercise-screens/IMG_3622.PNG"),
    ("Scissor Crunch", "Abdominal Tesoura", "Abs", "Bodyweight", "CORE", False, "/exercise-screens/IMG_3622.PNG"),
    ("Ab Wheel", "Roda Abdominal", "Abs", "Bodyweight", "CORE", False, "/exercise-screens/IMG_3622.PNG"),
    ("Treadmill Incline Walk", "Aeróbico", "Cardio", "Treadmill", "CARDIO", False, "/exercise-screens/IMG_3622.PNG"),
    ("Air Bike", "Bicicleta de Ar", "Cardio", "Machine", "CARDIO", False, "/exercise-screens/IMG_3622.PNG"),
    ("Arnold Press", "Desenvolvimento Arnold (halteres)", "Shoulders", "Dumbbell", "VERTICAL_PUSH", True, "/exercise-screens/IMG_3622.PNG"),
    ("Dumbbell Pullover", "Volta Ao Mundo", "Chest", "Dumbbell", "HORIZONTAL_PUSH", False, "/exercise-screens/IMG_3622.PNG"),
    ("Assisted Pistol Squat", "Agachamento Pistola Com Assistência", "Quadriceps", "Bodyweight", "SQUAT", True, "/exercise-screens/IMG_3622.PNG"),
    ("Smith Machine Bench Press", "Supino no Smith (Máquina)", "Chest", "Machine", "HORIZONTAL_PUSH", True, "/exercise-screens/IMG_3625.PNG"),
    ("Band Bent Over Row", "Remadas Dobradas (Banda Elástica)", "Back", "Band", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3625.PNG"),
    ("Barbell Bent Over Row", "Remadas Dobradas (Barra)", "Back", "Barbell", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3625.PNG"),
    ("Dumbbell Bent Over Row", "Remadas Dobradas (Halter)", "Back", "Dumbbell", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3625.PNG"),
    ("Cable Curl", "Rosca Direta na Polia", "Biceps", "Cable", "ISOLATION", False, "/exercise-screens/IMG_3625.PNG"),
    ("Dumbbell Curl", "Rosca Direta (Halter)", "Biceps", "Dumbbell", "ISOLATION", False, "/exercise-screens/IMG_3625.PNG"),
    ("Biceps Curl Machine", "Rosca Direta (Máquina)", "Biceps", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3625.PNG"),
    ("TRX Biceps Curl", "Bicep Curl Trx", "Biceps", "TRX", "ISOLATION", False, "/exercise-screens/IMG_3625.PNG"),
    ("Incline Chest Press", "Supino Inclinado", "Chest", "Machine", "HORIZONTAL_PUSH", True, "/exercise-screens/IMG_3620.PNG"),
    ("Lateral Raise Machine", "Elevação Lateral (Máquina)", "Shoulders", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Leg Extension", "Cadeira Extensora (Máquina)", "Quadriceps", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Hip Thrust Machine", "Hip Thrust (Máquina)", "Glutes", "Machine", "HIP_THRUST", True, "/exercise-screens/IMG_3621.PNG"),
    ("Standing Calf Raise", "Elevação de Gémeos em Pé", "Calves", "Machine", "ISOLATION", False, "/exercise-screens/IMG_3621.PNG"),
    ("Crunch Machine", "Abdominal Máquina", "Abs", "Machine", "CORE", False, "/exercise-screens/IMG_3622.PNG"),
    ("Plank", "Prancha", "Abs", "Bodyweight", "CORE", False, "/exercise-screens/IMG_3622.PNG"),
    ("Chest Supported Row", "Remada com Apoio de Peito", "Back", "Machine", "HORIZONTAL_PULL", True, "/exercise-screens/IMG_3621.PNG"),
]


def seed_catalog(apps, schema_editor):
    Exercise = apps.get_model("exercises", "Exercise")

    for name, localized_name, muscle_group, equipment, movement_pattern, is_compound, image_url in EXERCISE_CATALOG:
        Exercise.objects.update_or_create(
            name=name,
            defaults={
                "localized_name": localized_name,
                "muscle_group": muscle_group,
                "equipment": equipment,
                "movement_pattern": movement_pattern,
                "difficulty": "INTERMEDIATE",
                "is_compound": is_compound,
                "image_url": image_url,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_difficulty_exercise_is_compound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="localized_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_catalog, migrations.RunPython.noop),
    ]
