# =============================================================================
# 0005_exercise_weight_scale.py
# -----------------------------------------------------------------------------
# Migração Django da app exercises.
# É usada pelo sistema de migrations para criar ou alterar a estrutura da base de dados associada a exercises.
# O ficheiro 0005_exercise_weight_scale deve ser mantido como histórico técnico da evolução dos modelos e aplicado automaticamente pelo manage.py migrate.
# =============================================================================
# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_exercise_crop_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="main_weight_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="exercise",
            name="micro_weight_options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
