# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_exercise_crop_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="main_weight_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="exercise",
            name="micro_weight_options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
